version: "2"

services:
  tasks-golang:
    image: "tasks-golang"
    container_name: "tasks-golang"
    environment:
      - "TASKS_DATABASE_USER=root"
      - "TASKS_DATABASE_PASS=root"
      - "TASKS_DATABASE_HOST=tasks-mysql"
      - "TASKS_DATABASE_PORT=3306"
    volumes:
      - "../api:/go/src/example/tasks:cached"
    tty: "yes"

  tasks-mysql:
    image: "mysql:5.7"
    container_name: "tasks-mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      #- "MYSQL_USER=user1"
      #- "MYSQL_PASSWORD=userpassword"
      - "MYSQL_DATABASE=tasks"
      #- "TZ=Asia/Tokyo"
    volumes:
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "tasks-mysql:/var/lib/mysql:cached"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"

  tasks-nginx:
    image: "nginx:alpine"
    container_name: "tasks-nginx"
    ports:
      - "80:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"

  tasks-api-database:
    image: "tasks-api-database"
    container_name: "tasks-api-database"
    environment:
      - "TASKS_DATABASE_USER=root"
      - "TASKS_DATABASE_PASS=root"
      - "TASKS_DATABASE_HOST=tasks-mysql"
      - "TASKS_DATABASE_PORT=3306"

  tasks-api-task:
    image: "tasks-api-task"
    container_name: "tasks-api-task"
    environment:
      - "TASKS_API_HOST=tasks-nginx"
      - "TASKS_API_PORT=80"

  tasks-api-tasks:
    image: "tasks-api-tasks"
    container_name: "tasks-api-tasks"
    environment:
      - "TASKS_API_HOST=tasks-nginx"
      - "TASKS_API_PORT=80"

volumes:
  tasks-mysql:
    driver: "local"
