version: "3"

services:
  tasks-golang:
    image: "tasks-golang"
    container_name: "tasks-golang"
    working_dir: "/go/src/github.com/becosuke/tasks-api"
    volumes:
      - "../tasks-api:/go/src/github.com/becosuke/tasks-api:cached"
    tty: "yes"

  tasks-mysql:
    image: "mysql:5.7"
    container_name: "tasks-mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      #- "MYSQL_USER=user1"
      #- "MYSQL_PASSWORD=userpassword"
      - "MYSQL_DATABASE=tasks"
      #- "TZ=Asia/Tokyo"
    volumes:
      - "./mysql/files/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "./mysql/data/var/lib/mysql:/var/lib/mysql:cached"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"

  tasks-nginx:
    image: "nginx:alpine"
    container_name: "tasks-nginx"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "./nginx/files/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/files/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"

  tasks-view:
    image: "node:8-alpine"
    container_name: "tasks-view"
    user: "node"
    working_dir: "/opt/tasks"
    volumes:
      - "../view:/opt/tasks:cached"
    tty: "yes"
    command: "/bin/sh"
    ports:
      - "3000:3000"

  tasks-api:
    image: "tasks-api"
    container_name: "tasks-api-task"
