version: "2"

services:
  tasks-golang:
    image: "tasks-golang"
    container_name: "tasks-golang"
    volumes:
      - "..:/go/src/example/tasks:cached"
    tty: "yes"

  tasks-mysql:
    image: "mysql:5.7"
    container_name: "tasks-mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      #- "MYSQL_USER=user1"
      #- "MYSQL_PASSWORD=userpassword"
      - "MYSQL_DATABASE=tasks"
      #- "TZ=Asia/Tokyo"
    volumes:
      - "./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro"
      - "tasks-mysql:/var/lib/mysql:cached"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"

  tasks-dbi:
    image: "tasks-dbi"
    container_name: "tasks-dbi"
    environment:
      - "TASKS_DB_USER=root"
      - "TASKS_DB_PASS=root"
      - "TASKS_DB_HOST=tasks-mysql"
      - "TASKS_DB_PORT=3306"

  tasks-api:
    image: "nginx:alpine"
    container_name: "tasks-api"
    ports:
      - "8080:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"

  tasks-api-task:
    image: "tasks-api-task"
    container_name: "tasks-api-task"
    environment:
      - "TASKS_DBI_HOST=tasks-dbi"
      - "TASKS_DBI_PORT=8080"

  tasks-api-tasks:
    image: "tasks-api-tasks"
    container_name: "tasks-api-tasks"
    environment:
      - "TASKS_DBI_HOST=tasks-dbi"
      - "TASKS_DBI_PORT=8080"

volumes:
  tasks-mysql:
    driver: "local"
